# Generated by Django 4.1.7 on 2023-04-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='onOffer',
            field=models.BooleanField(default=True),
        ),
    ]
