# Generated by Django 4.1.7 on 2023-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='other_images',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
