# Generated by Django 4.2.2 on 2023-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_item_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='other_images',
        ),
    ]
